// Camera Settings
#declare DebugCameraLocation = <0,0,0>;
#declare DebugCameraLookAt = <0, 0, 0>;

#declare BrowserTrafficCameraLocation = <0, 0, 0>;
#declare BrowserTrafficCameraLookAt = <0, 0, 0>;

#declare SearchCategoryCameraLocation = <0, 0, 0>;
#declare SearchCategoryCameraLookAt = <0, 0, 0 >;

#declare SceneCameraLocation = <0, 0, 0>;
#declare SceneCameraLookAt = <0, 0, 0>;


#declare camera_location = <0, 12, 0>;
#declare lookat_location = <0,3,60>;
#declare LookAtSearchCategories = <-60, 12, 0>;
#declare ViewDistance = 20;
